import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'DreamDojo × π0.5 · Parallel Worlds Lab',
  description:
    'Explore multiple π0.5 action samples as parallel DreamDojo futures from the same recorded Jokeru observation.',
  openGraph: {
    title: 'DreamDojo × π0.5 · Parallel Worlds Lab',
    description:
      'One recorded observation, three π0.5 action chunks, and three action-conditioned DreamDojo futures.',
    images: [
      {
        url: '/dreamdojo-jokeru-og.png',
        width: 1200,
        height: 630,
        alt: 'DreamDojo Jokeru evaluation dashboard preview',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'DreamDojo × π0.5 · Parallel Worlds Lab',
    description:
      'Parallel robot futures sampled with π0.5 and generated by DreamDojo 2B.',
    images: ['/dreamdojo-jokeru-og.png'],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
